### ISSUE TITLE
crashes on startup on mac

### ISSUE THREAD

**Issue by brlcad** [liamg/darktile#290]
**Describe the bug**

Crashes immediately on startup on Mac 10.14 with or without options:

**To Reproduce**
1. Run ./aminal-darwin-amd64 from Terminal 
2. See error

**Expected behavior**
Not bomb.

**Screenshots**
```
agua:Downloads morrison$ ./aminal-darwin-amd64  --ignore-config --debug
2020-09-14T15:48:32.932-0400	INFO	aminal/main.go:54	Allocating pty...
2020-09-14T15:48:33.023-0400	INFO	aminal/main.go:79	Creating terminal...
2020-09-14T15:48:33.023-0400	DEBUG	gui/gui.go:376	Creating window...
2020-09-14T15:48:35.218-0400	DEBUG	gui/gui.go:387	Initialising OpenGL and creating program...
2020-09-14T15:48:35.541-0400	INFO	gui/gui.go:855	OpenGL version 4.1 NVIDIA-12.0.24 355.11.10.50.10.103
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.throw(0x44468fd, 0x2a)
	/Users/travis/.gimme/versions/go1.11.13.darwin.amd64/src/runtime/panic.go:608 +0x72
runtime.sigpanic()
	/Users/travis/.gimme/versions/go1.11.13.darwin.amd64/src/runtime/signal_unix.go:374 +0x2f2
runtime.asmcgocall(0x0, 0x0)
	/Users/travis/.gimme/versions/go1.11.13.darwin.amd64/src/runtime/asm_amd64.s:641 +0x70

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4331890, 0xc00013ba40, 0x4b9abc0)
	/Users/travis/.gimme/versions/go1.11.13.darwin.amd64/src/runtime/cgocall.go:128 +0x5e fp=0xc00013ba10 sp=0xc00013b9d8 pc=0x400512e
github.com/liamg/aminal/vendor/github.com/go-gl/gl/all-core/gl._Cfunc_glowDebugMessageCallback(0x0, 0xc000180018, 0x0)
	_cgo_gotypes.go:7030 +0x45 fp=0xc00013ba40 sp=0xc00013ba10 pc=0x42b5245
github.com/liamg/aminal/vendor/github.com/go-gl/gl/all-core/gl.DebugMessageCallback.func1(0x0, 0xc000180018, 0x0)
	/Users/travis/gopath/src/github.com/liamg/aminal/vendor/github.com/go-gl/gl/all-core/gl/package.go:11529 +0x6a fp=0xc00013ba78 sp=0xc00013ba40 pc=0x42d5dca
github.com/liamg/aminal/vendor/github.com/go-gl/gl/all-core/gl.DebugMessageCallback(0xc00018a080, 0x0)
	/Users/travis/gopath/src/github.com/liamg/aminal/vendor/github.com/go-gl/gl/all-core/gl/package.go:11529 +0x6d fp=0xc00013baa0 sp=0xc00013ba78 pc=0x42b85ed
github.com/liamg/aminal/gui.(*GUI).createProgram(0xc0000e08c0, 0x4446a7c, 0x2b, 0x0)
	/Users/travis/gopath/src/github.com/liamg/aminal/gui/gui.go:859 +0x32f fp=0xc00013bb28 sp=0xc00013baa0 pc=0x431392f
github.com/liamg/aminal/gui.(*GUI).Render(0xc0000e08c0, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/liamg/aminal/gui/gui.go:388 +0x215 fp=0xc00013be28 sp=0xc00013bb28 pc=0x430fd25
main.initialize(0x0, 0x0)
	/Users/travis/gopath/src/github.com/liamg/aminal/main.go:101 +0x4f4 fp=0xc00013bf78 sp=0xc00013be28 pc=0x4320854
main.main()
	/Users/travis/gopath/src/github.com/liamg/aminal/main.go:25 +0x29 fp=0xc00013bf98 sp=0xc00013bf78 pc=0x4320349
runtime.main()
	/Users/travis/.gimme/versions/go1.11.13.darwin.amd64/src/runtime/proc.go:201 +0x207 fp=0xc00013bfe0 sp=0xc00013bf98 pc=0x402e677
runtime.goexit()
	/Users/travis/.gimme/versions/go1.11.13.darwin.amd64/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc00013bfe8 sp=0xc00013bfe0 pc=0x405a401

goroutine 11 [chan receive]:
main.initialize.func1(0xc0000a20a0, 0xc00000e088)
	/Users/travis/gopath/src/github.com/liamg/aminal/main.go:39 +0x37
created by main.initialize
	/Users/travis/gopath/src/github.com/liamg/aminal/main.go:37 +0x11c

goroutine 19 [syscall]:
syscall.Syscall6(0x7, 0x1ae2, 0xc000547e1c, 0x0, 0xc000124090, 0x0, 0x0, 0xc000124090, 0x0, 0xc000047800)
	/Users/travis/.gimme/versions/go1.11.13.darwin.amd64/src/syscall/asm_darwin_amd64.s:41 +0x5
syscall.wait4(0x1ae2, 0xc000547e1c, 0x0, 0xc000124090, 0x90, 0x4420d40, 0x1)
	/Users/travis/.gimme/versions/go1.11.13.darwin.amd64/src/syscall/zsyscall_darwin_amd64.go:34 +0x7b
syscall.Wait4(0x1ae2, 0xc000547e6c, 0x0, 0xc000124090, 0x0, 0x0, 0x0)
	/Users/travis/.gimme/versions/go1.11.13.darwin.amd64/src/syscall/syscall_bsd.go:129 +0x51
os.(*Process).wait(0xc00015a030, 0x0, 0x0, 0x0)
	/Users/travis/.gimme/versions/go1.11.13.darwin.amd64/src/os/exec_unix.go:38 +0x7b
os.(*Process).Wait(0xc00015a030, 0x0, 0x0, 0x0)
	/Users/travis/.gimme/versions/go1.11.13.darwin.amd64/src/os/exec.go:125 +0x2b
os/exec.(*Cmd).Wait(0xc000154000, 0x0, 0x0)
	/Users/travis/.gimme/versions/go1.11.13.darwin.amd64/src/os/exec/exec.go:465 +0x5b
github.com/liamg/aminal/platform.(*cmdProc).Wait(0xc000114010, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/liamg/aminal/platform/cmdProc.go:18 +0x2e
main.initialize.func3(0x491e120, 0xc000114010, 0xc00000e088, 0xc0000e08c0)
	/Users/travis/gopath/src/github.com/liamg/aminal/main.go:94 +0x35
created by main.initialize
	/Users/travis/gopath/src/github.com/liamg/aminal/main.go:93 +0x5c0
agua:Downloads morrison$ 
```

**Comment by brlcad** [comment]
This was Aminal Nightly-develop-2020-01-26-4033a8b

**Comment by liamg** [comment]
Closed due to complete rewrite as part of bringing the project back to life, please create a new issue if still relevant. Thank you!
